# step 1: 环境确认

In [1]:
import numpy
import scipy
import matplotlib
import pandas
import mne
import sklearn
import torch

print("Environment OK")

Environment OK


# step2 GDF数据读取
    mne包；
        MNE = Magnetoencephalography / Electroencephalography 的开源 Python 库，专门处理神经影像数据。



In [2]:
import mne


file_path = "D:\\EEG_BCI_Project\\data\\raw\\BCICIV_2a_gdf\\A01T.gdf"


raw = mne.io.read_raw_gdf(
    file_path,
    preload=True
)


print(raw)

print("----------------")

print(raw.ch_names)

print("----------------")

print(raw.info)

Extracting GDF parameters from D:\EEG_BCI_Project\data\raw\BCICIV_2a_gdf\A01T.gdf...
Setting channel info structure...
Could not determine channel type of the following channels, they will be set as EEG:
EEG-Fz, EEG, EEG, EEG, EEG, EEG, EEG, EEG-C3, EEG, EEG-Cz, EEG, EEG-C4, EEG, EEG, EEG, EEG, EEG, EEG, EEG, EEG-Pz, EEG, EEG, EOG-left, EOG-central, EOG-right
Creating raw.info structure...
Reading 0 ... 672527  =      0.000 ...  2690.108 secs...


D:\python\Lib\contextlib.py:148: RuntimeWarning: Channel names are not unique, found duplicates for: {'EEG'}. Applying running numbers for duplicates.
  next(self.gen)


<RawGDF | A01T.gdf, 25 x 672528 (2690.1 s), ~128.3 MiB, data loaded>
----------------
['EEG-Fz', 'EEG-0', 'EEG-1', 'EEG-2', 'EEG-3', 'EEG-4', 'EEG-5', 'EEG-C3', 'EEG-6', 'EEG-Cz', 'EEG-7', 'EEG-C4', 'EEG-8', 'EEG-9', 'EEG-10', 'EEG-11', 'EEG-12', 'EEG-13', 'EEG-14', 'EEG-Pz', 'EEG-15', 'EEG-16', 'EOG-left', 'EOG-central', 'EOG-right']
----------------
<Info | 8 non-empty values
 bads: []
 ch_names: EEG-Fz, EEG-0, EEG-1, EEG-2, EEG-3, EEG-4, EEG-5, EEG-C3, EEG-6, ...
 chs: 25 EEG
 custom_ref_applied: False
 highpass: 0.5 Hz
 lowpass: 100.0 Hz
 meas_date: 2005-01-17 12:00:00 UTC
 nchan: 25
 projs: []
 sfreq: 250.0 Hz
 subject_info: <subject_info | his_id: A01, sex: 0, last_name: X, birthday: 1983-01-17>
>


<RawGDF | A01T.gdf, 25 x 672528 (2690.1 s), ~128.3 MiB, data loaded>
ch_names: EEG-Fz, EEG-0, EEG-1, EEG-2, EEG-3, EEG-4, EEG-5, EEG-C3, EEG-6, ...
 chs: 25 EEG
 highpass: 0.5 Hz
 lowpass: 100.0 Hz
 meas_date: 2005-01-17 12:00:00 UTC
 nchan: 25
 projs: []
 sfreq: 250.0 Hz

In [3]:
raw

<RawGDF | A01T.gdf, 25 x 672528 (2690.1 s), ~128.3 MiB, data loaded>

In [4]:
events, event_dict = mne.events_from_annotations(raw)


print("事件字典:")
print(event_dict)


print("----------------")


print("事件数量:")
print(len(events))


print("----------------")


print("前10个事件:")
print(events[:10])

import numpy as np


labels = events[:,2]


for event_id in [7,8,9,10]:

    count = np.sum(labels == event_id)

    print(
        event_id,
        "数量:",
        count
    )

Used Annotations descriptions: [np.str_('1023'), np.str_('1072'), np.str_('276'), np.str_('277'), np.str_('32766'), np.str_('768'), np.str_('769'), np.str_('770'), np.str_('771'), np.str_('772')]
事件字典:
{np.str_('1023'): 1, np.str_('1072'): 2, np.str_('276'): 3, np.str_('277'): 4, np.str_('32766'): 5, np.str_('768'): 6, np.str_('769'): 7, np.str_('770'): 8, np.str_('771'): 9, np.str_('772'): 10}
----------------
事件数量:
603
----------------
前10个事件:
[[    0     0     5]
 [    0     0     3]
 [29683     0     5]
 [29683     0     4]
 [49955     0     5]
 [49955     0     2]
 [91518     0     5]
 [91868     0     6]
 [92368     0    10]
 [93871     0     6]]
7 数量: 72
8 数量: 72
9 数量: 72
10 数量: 72


读到的名	真实名	脑区
EEG-Fz	Fz	额叶中线
EEG-0	FC3	额中央左
EEG-1	FC1	额中央左中线
EEG-2	FCz	额中央中线
EEG-3	FC2	额中央右中线
EEG-4	FC4	额中央右
EEG-5	C5	中央左外侧
# EEG-C3	C3	中央左（运动区）
EEG-6	C1	中央左中线
# EEG-Cz	Cz	中央顶点
EEG-7	C2	中央右中线
# EEG-C4	C4	中央右（运动区）
EEG-8	C6	中央右外侧
EEG-9	CP3	中央顶左
EEG-10	CP1	中央顶左中线
EEG-11	CPz	中央顶中线
EEG-12	CP2	中央顶右中线
EEG-13	CP4	中央顶右
EEG-14	P1	顶叶左中线
EEG-Pz	Pz	顶叶中线
EEG-15	P2	顶叶右中线
EEG-16	POz	顶枕中线
EOG-left	EOG-left	左眼电
EOG-central	EOG-central	中央眼电
EOG-right	EOG-right	右眼电

In [1]:
import torch

print(torch.__version__)

print("CUDA available:")
print(torch.cuda.is_available())

2.13.0+cu126
CUDA available:
True


很好，**Step 9：基础CNN模型训练完成。**

这是你项目中第一个真正的深度学习实验结果，而且GPU已经成功参与训练。

先进行结果判断。

---

# 1. GPU训练确认

你的输出：

```text
Device: cuda
```

说明：

✅ PyTorch成功调用RTX 4060
✅ 模型在GPU训练
✅ CUDA环境配置完成

这一部分已经成功。

---

# 2. CNN训练过程分析

训练Loss：

开始：

```text
Epoch 1:
Loss=20.4889
```

结束：

```text
Epoch 50:
Loss=10.8530
```

变化：

```text
20.49
 ↓
10.85
```

说明：

模型确实学习到了部分EEG模式。

但是下降速度较慢，并且后期震荡：

例如：

```text
Epoch 35:
12.8174

Epoch 46:
10.7540

Epoch 49:
11.1819
```

说明：

模型已经接近当前结构能力上限。

---

# 3. CNN Accuracy结果

你的结果：

```text
CNN Accuracy:
0.41379310344827586
```

即：

[
Accuracy=41.38%
]

和传统机器学习比较：

| 方法            | 输入      | Accuracy |
| ------------- | ------- | -------: |
| LDA           | CSP     |   67.24% |
| SVM           | CSP     |   75.86% |
| Random Forest | CSP     |   77.59% |
| CNN           | Raw EEG |   41.38% |

---

# 4. 这个结果正常吗？

正常。

对于第一次CNN baseline：

**不是失败，而是一个重要实验结果。**

原因：

## 原因1：数据量太小

你现在：

```text
288 trials
```

深度学习非常吃数据。

CNN参数：

可能：

```text
几千~几万个参数
```

但是训练样本：

```text
288
```

容易：

* 欠拟合
* 泛化差

---

## 原因2：运动想象EEG非常难

EEG特点：

* 信噪比低
* 个体差异大
* 空间关系复杂

简单CNN：

不能很好提取：

* Mu rhythm
* Beta rhythm
* 空间滤波特征

---

## 原因3：CSP本身非常强

传统机器学习：

你的流程：

```text
EEG
 ↓
CSP
 ↓
分类器
```

CSP已经人为强化：

运动想象相关空间模式。

所以：

SVM/RF达到75%以上很正常。

---

# 5. 但是这个结果对论文很有价值

你的研究题目：

> 基于EEG信号的运动想象脑机接口分类研究：机器学习与深度学习方法比较

你现在已经有：

## 传统方法结果

```text
CSP + RF

77.59%
```

## 深度学习baseline

```text
Raw EEG + CNN

41.38%
```

这说明：

> 在小规模单被试数据条件下，传统特征工程方法仍具有优势。

这是一个合理的科研结论。

---

# 6. 但是我们不能停在这里

论文中的深度学习部分需要优化。

下一步不是直接换模型，而是先做**实验规范化**。

目前CNN还有几个问题：

---

## 问题1：没有验证集

现在：

```text
train/test
```

只有：

```text
80%训练
20%测试
```

论文不够规范。

应该：

```text
训练集
 ↓
验证集
 ↓
测试集
```

---

## 问题2：没有保存最佳模型

现在：

Epoch 50结束直接测试。

但是：

最佳epoch可能在：

```text
Epoch 37
```

或者：

```text
Epoch 46
```

---

## 问题3：没有混淆矩阵

目前不知道：

CNN到底哪里错。

例如：

可能：

```
left hand
容易识别

feet
容易混淆
```

---

## 问题4：CNN结构太普通

当前：

```text
Conv2D
 ↓
Conv2D
 ↓
Pooling
```

但是EEG论文常用：

* EEGNet
* DeepConvNet
* ShallowConvNet

尤其：

## EEGNet

是BCI Competition数据集最经典模型之一。

---

# 下一步安排

我们进入：

# Step 10：CNN结果分析与优化

顺序：

---

## Step 10.1 保存实验结果

生成：

```text
results/logs/cnn_result.txt
```

记录：

```text
Model:
CNN

Input:
Raw EEG

Accuracy:
41.38%

Device:
CUDA
```

---

## Step 10.2 添加混淆矩阵

生成：

```text
results/figures/cnn_confusion_matrix.png
```

用于论文。

---

## Step 10.3 改进CNN

加入：

* Dropout
* Early stopping
* Learning rate scheduler

目标：

看看CNN能否从：

```text
41%
```

提升到：

```text
50%-60%
```

---

然后进入：

# Step 11：EEGNet

目标：

超过传统方法或者接近：

```text
70%+
```

因为：

EEGNet专门为EEG设计。

---

现在先做 **Step 10.1 + Step 10.2**。

我们先不要急着改模型。

请你创建：

```
scripts/utils/analyze_cnn.py
```

下一步我会给你代码，用于生成：

1. CNN测试结果报告
2. 混淆矩阵图片
3. 分类报告

这样你的项目从“跑模型”进入“科研实验记录阶段”。
